name: cd-gcp

on:
  # Allows manual runs from GitHub Actions UI
  workflow_dispatch:
  push:
    # Trigger whenever a new tag starting with v... is pushed
    tags:
      - "v**"

jobs:
  gcp:
    name: GCP Cloud Run
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Authenticate to GCP using a Service Account Key stored in GitHub Secrets
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Authenticate Docker against Google Artifact Registry
      - name: Set up Cloud SDK & Docker Login
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      # Build and Push Image to Google Artifact Registry
      # Build and push image to Artifact Registry
      - name: Build and push image to Artifact Registry
        env:
          GCP_REGION: us-central1
          GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
          REPOSITORY: fragments
          IMAGE_NAME: fragments-frontend
          VERSION_TAG: ${{ github.ref_name }}
        uses: docker/build-push-action@v6
        with:
          push: true
          # Default context and Dockerfile now automatically point to the repository root
          tags: |
            ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION_TAG }}
            ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
            
      # Deploy directly to Google Cloud Run
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: fragments-service
          region: us-central1
          image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fragments/fragments:${{ github.ref_name }}
          env_vars: |
            LOG_LEVEL=DEBUG
            NODE_ENV=PRODUCTION
            AWS_COGNITO_POOL_ID=${{ secrets.AWS_COGNITO_POOL_ID }}
            AWS_COGNITO_CLIENT_ID=${{ secrets.AWS_COGNITO_CLIENT_ID }}
            API_URL=http://fragments-lb-1586106384.us-east-1.elb.amazonaws.com